### ISSUE TITLE
Free emojis related

### ISSUE THREAD

**Issue by eddytyler** [DarkRabbit-0/discord-js#2]
I just wanted to say can't u try to make one for free boosts like free emojis ?????

**Comment by therealtear** [comment]
> I just wanted to say can't u try to make one for free boosts like free emojis ?????

( ͡° ͜ʖ ͡°)

**Comment by Proxysec** [comment]
Please look up what client side is, so nothing will effect your server side profile.

**Comment by therealtear** [comment]
> Please look up what client side is, so nothing will effect your server side profile.

This^^^

**Comment by Proxysec** [comment]
> > Please look up what client side is, so nothing will effect your server side profile.
> 
> This^^^

Correct
